name: build

permissions:
  contents: write

on: push

env:
  MainBranch: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Deno Setup
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x.x

      - name: Deno Build
        run: deno task build

      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          # major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          # minor_regexp_flags: ""
          version_format: ${{ steps.vars.outputs.branchName == env.MainBranch ? "${major}.${minor}.${patch}" : "${major}.${minor}.${patch}-prerelease${increment}" }}
          namespace: ${{ steps.vars.outputs.branchName == env.MainBranch ? "" : "biotech-atomic" }}
          bump_each_commit: false
          search_commit_body: false
          user_format_type: "json"
          enable_prerelease_mode: true

      - name: Tag commit ${{ steps.version.outputs.version_tag }}
        # if: ${{ fromJSON(steps.changed.outputs.result) }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.version_tag }} ${{ steps.commit.outputs.commit }}
          git push origin ${{ steps.version.outputs.version_tag }}
          