name: build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Deno Setup
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x.x

      - name: Install semver
        run: npm install --global semver

      - name: Get current commit
        run: echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Get current version
        id: semver
        run: echo "::set-output name=version::$(semver -l | cut -c 2-)"

      - name: Deno Build
        run: deno task build

      - name: Tag commit ${{ steps.semver.outputs.version }}
        # if: ${{ fromJSON(steps.changed.outputs.result) }}
        env:
          GITHUB_TOKEN: ${{ secrets.FATHYM_GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.semver.outputs.version }} ${{ steps.commit.outputs.commit }}
        # git push origin ${{ steps.semver.outputs.version }}
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}