name: build

permissions:
  contents: write

on: push

env:
  MainBranch: main
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set variables
        id: vars
        run: |
          echo "currentBranch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Set version format
        id: mainFormat
        if: steps.vars.outputs.currentBranch == env.MainBranch
        run: echo "format=${{ env.MainFormat }}" >> $GITHUB_OUTPUT\

      - name: Set version format
        id: prereleaseFormat
        if: steps.vars.outputs.currentBranch == env.MainBranch
        run: echo "format=${{ env.MainFormat }}-${{ steps.vars.outputs.currentBranch }}(increment)" >> $GITHUB_OUTPUT\

      - name: Deno Setup
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x.x

      - name: Deno Build
        run: deno task build

      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: ${{ steps.mainFormat.outputs.format || steps.prereleaseFormat.outputs.format }}
          # namespace: ${{ steps.vars.outputs.currentBranch == env.MainBranch && null || steps.vars.outputs.currentBranch }}
          # bump_each_commit: false
          # search_commit_body: false
          user_format_type: "json"
          enable_prerelease_mode: true

      - name: Tag commit ${{ steps.version.outputs.version }}
        run: |
          git tag v${{ steps.version.outputs.version }} ${{ steps.commit.outputs.commit }}
          git push origin ${{ steps.version.outputs.version }}
          